package com.blendwerk.pet.domain;

public enum ExpenseCategory {
    GROCERIES,
    UTILITIES,
    RENT_MORTGAGE,
    TRANSPORTATION,
    ENTERTAINMENT,
    DINING_OUT,
    HEALTHCARE,
    INSURANCE,
    EDUCATION,
    PERSONAL_CARE,
    CLOTHING,
    TRAVEL,
    GIFTS_DONATIONS,
    SUBSCRIPTIONS_MEMBERSHIPS,
    CHILDCARE,
    PET_CARE,
    HOME_IMPROVEMENT,
    TAXES,
    SAVINGS_INVESTMENTS,
    DEBT_REPAYMENT,
    OTHER
}